In [1]:
from pythreejs import *
from ipywidgets import *
from IPython.display import display
import numpy as np
import util
import manipulator
import time
from scipy.spatial.transform import Rotation as R, Slerp
import pythreejs as three

np.set_printoptions(precision=3, suppress=True)
env = util.Environment()
env.light.position = [5,5,25]

#env.add(util.create_grid_XY(size = 15, density= 0.5, pos=[0,0,0.5], color ="#0098D4"))



#robot = manipulator.Manipulator("kr5_arc")             #läuft vermutlich wegen experimental nicht
#robot = manipulator.Manipulator("kr210l150")         #läuft vermutlich wegen experimental nicht
#robot = manipulator.Manipulator("irb52_7_145")
#robot = manipulator.Manipulator("irb120t_3_58")
#robot = manipulator.Manipulator("kr150_2")
#robot = manipulator.Manipulator("irb6640_185_280")
#robot = manipulator.Manipulator("irb1200_7_70")
#robot = manipulator.Manipulator("crb15000_5_95")
#robot = manipulator.Manipulator("lbr_iiwa_14_r820")
robot = manipulator.Manipulator("kr6r900_2")



for i in range(len(robot.joints)):
    env.add_gizmo_controls(robot.joints[i], True, True, True, robot.joints[i].name)


env.add([robot])
display(env)
robot.set_opacity(0.7, False)


#irb6640_185_280
#dh_parameters : dict= {}
#dh_parameters[robot.joints[0].name] = {"theta":0,        "d":0.78,   "a":0,      "alpha":0}
#dh_parameters[robot.joints[1].name] = {"theta":0,        "d":0,      "a":0.32,   "alpha":np.pi/2}
#dh_parameters[robot.joints[2].name] = {"theta":np.pi/2,  "d":0,      "a":1.075,  "alpha":0}
#dh_parameters[robot.joints[3].name] = {"theta":0,        "d":0,      "a":0.2,    "alpha":np.pi/2}
#dh_parameters[robot.joints[4].name] = {"theta":0,        "d":1.392,  "a":0,      "alpha":-np.pi/2}
#dh_parameters[robot.joints[5].name] = {"theta":0,        "d":0,      "a":0,      "alpha":np.pi/2}
#dh_parameters[robot.joints[6].name] = {"theta":0,        "d":0.2,    "a":0,      "alpha":0}
#DH = manipulator.DHKinematicModel(dh_parameters=dh_parameters)

#kr6r900_2
dh_parameters : dict= {}
dh_parameters[robot.joints[1].name] = {"theta":0,        "d":0,      "a":0.025,   "alpha":np.pi/2}
dh_parameters[robot.joints[2].name] = {"theta":0,        "d":0,      "a":0.455,   "alpha":0}
dh_parameters[robot.joints[3].name] = {"theta":np.pi/2,  "d":0,      "a":0.025,   "alpha":np.pi/2}
dh_parameters[robot.joints[4].name] = {"theta":0,        "d":0.42,   "a":0,       "alpha":-np.pi/2}
dh_parameters[robot.joints[5].name] = {"theta":0,        "d":0,      "a":0,       "alpha":np.pi/2}
dh_parameters[robot.joints[7].name] = {"theta":0,        "d":0.09,   "a":0,       "alpha":0}
print(robot.joints[7].name)

base_transform = manipulator.pose_to_matrix(robot.base_to_baselink_joint.get_position(), robot.base_to_baselink_joint.get_rotation(False), False)
base_transform_inv = np.linalg.inv(base_transform)
k0 = manipulator.compute_dh_matrix(0.0, 0.4, 0.0, 0.0)
base_to_dh = base_transform_inv @ k0

DH = manipulator.DHKinematicModel(dh_parameters=dh_parameters, base_to_dh=base_to_dh)
DH.dh_to_tool = DH.compute_dh_to_tool(robot.compute_global_transform()[robot.link_to_flange_joint.name])


robot.apply_DH_model(DH)
robot.show_DH_frames()

#dh_transforms = DH.compute_transforms()
#last_key = next(reversed(dh_transforms))
#last_dh = dh_transforms[last_key]
#print(f"last_dh:\n{last_dh}")
#print(f"\n dh_to_tool:\n{DH.dh_to_tool}")

print(robot.get_global_tcp_transform())



c:\Users\Philipp\Desktop\gitProjects\visualkinematics_v2\.venv\lib\site-packages\IPython\core\interactiveshell.py:3579: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  exec(code_obj, self.user_global_ns, self.user_ns)


joint_6-flange
[[1.    0.    0.    0.99 ]
 [0.    1.    0.    0.   ]
 [0.    0.    1.    0.425]
 [0.    0.    0.    1.   ]]


c:\Users\Philipp\Desktop\gitProjects\visualkinematics_v2\src\manipulator.py:809: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  self.compute_global_transform(child, current_transform, global_transforms)


In [9]:
robot.animate_stable(robot.joints, [np.pi/2 for _ in range(6)], 4)

6


In [13]:
print(robot.get_global_tcp_transform())

[[ 0.612  0.     0.791  0.812]
 [-0.     1.    -0.    -0.   ]
 [-0.791 -0.     0.612  0.012]
 [ 0.     0.     0.     1.   ]]


In [2]:
print(robot.get_global_tcp_position())

KeyError: 'tool0'

In [6]:
joints = [robot.joints[0], robot.joints[1], robot.joints[2], robot.joints[3], robot.joints[4], robot.joints[5]]

robot.animate_experimental(joints, [np.pi/2 for _ in range(6)], 4, 1)


In [ ]:
manipulator.apply_joint_angle(robot.joints[0], robot.joints[0].axis, 0)
manipulator.apply_joint_angle(robot.joints[1], robot.joints[1].axis, 0)
manipulator.apply_joint_angle(robot.joints[2], robot.joints[2].axis, 0)
manipulator.apply_joint_angle(robot.joints[3], robot.joints[3].axis, 0)
manipulator.apply_joint_angle(robot.joints[4], robot.joints[4].axis, 0)

meshes = [robot.joints[4].get_renderable(), robot.joints[3].get_renderable(), robot.joints[2].get_renderable(), robot.joints[1].get_renderable(), robot.joints[0].get_renderable()]

i = 0
while(i < 4000):
    with Widget.hold_sync(meshes[0]):
        with Widget.hold_sync(meshes[1]):
            with Widget.hold_sync(meshes[2]):
                with Widget.hold_sync(meshes[3]):
                    with Widget.hold_sync(meshes[4]): 
                        manipulator.apply_joint_rotation(robot.joints[4], robot.joints[4].axis, -np.pi/600)
                        #time.sleep(0.04)
                        manipulator.apply_joint_rotation(robot.joints[3], robot.joints[3].axis, np.pi/200)
                        #time.sleep(0.04)
                        manipulator.apply_joint_rotation(robot.joints[2], robot.joints[2].axis, -np.pi/800)
                        #time.sleep(0.04)
                        manipulator.apply_joint_rotation(robot.joints[1], robot.joints[1].axis, np.pi/800)
                        #time.sleep(0.04)
                        manipulator.apply_joint_rotation(robot.joints[0], robot.joints[0].axis, np.pi/400)
                        i+=1
                        time.sleep(0.01)








TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'R': Cannot determine Numba type of <class 'type'>

File "manipulator.py", line 482:
def apply_joint_angle(joint: Joint, axis, angle_rad):
    <source elided>
    axis = axis / np.linalg.norm(axis)  # Normalisieren
    r = R.from_rotvec(axis * angle_rad)  # Rotationsvektor → Quaternion
    ^

During: Pass nopython_type_inference 

This error may have been caused by the following argument(s):
- argument 0: Cannot determine Numba type of <class 'manipulator.Joint'>


In [ ]:
print("----------------------")
print(f"base: {robot.base.name}")
print(f"base_link: {robot.base_link.name}")
print(f"base_to_baselink_joint: {robot.base_to_baselink_joint.name}")
print(f"flange_to_tool_joint: {robot.flange_to_tool_joint.name}")
print(f"flange: {robot.flange.name}")
print(f"base_link_to_joint_1: {robot.base_link_to_link_1_joint.name}")
print("----------------------")