In [6]:
import numpy as np

D = np.array([
    [0,  0, 1, 0.99],
    [0, -1, 0,    0],
    [1,  0, 0, 0.43],
    [0,  0, 0,    1]
])

tool = np.array([
 [1,    0,     0,    0.99],
 [0,    1,    0,    0,   ],
 [0,    0,    1,    0.43 ],
 [0,    0,    0,    1,   ],
])

T = np.linalg.inv(D) @ tool
print(T)
print()
print(D @ T)

[[ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]

[[1.   0.   0.   0.99]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   0.43]
 [0.   0.   0.   1.  ]]
